POST http://localhost:5000/api/places
Content-Type: application/json

{
    "title": "Ainola",
    "description": "Turistikohde",
    "open_from": "9",
    "open_to": "15",
    "lat": "60.455319470716816",
    "lng": "25.0867132310072"
}