PUT http://localhost:5000/api/places/1
Content-Type: application/json

{
    "title": "Gotham",
    "description": "Batmans home",
    "open_from": "7",
    "open_to": "17",
    "coordinates": "xxx"
}